# Generated by Django 6.0.5 on 2026-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField()),
                ("telefone", models.TextField(null=True)),
            ],
        ),
    ]
